In [2]:
import json
import numpy as np
import pandas as pd

In [2]:
dat = pd.read_csv("/home/vitt/Документы/data/gazprom/Moskow.csv", sep='\t')

In [3]:
dat.head()

ID     Широта   \Долгота  Регион Тип региона \Тип области     Область  \
0  529360  55.655923  37.541505  Москва           г            г      Москва   
1  529366  55.670133  37.552418  Москва           г            г      Москва   
2  529368  55.783686  37.560107  Москва           г            г      Москва   
3  529372  55.619560  37.464870  Москва           г            п  Мосрентген   
4  529376  55.746765  37.626585  Москва           г            г      Москва   

                                        Полный адрес  \
0         г. Москва, ул. Профсоюзная, д. 61, корп. А   
1                  г. Москва, ул. Профсоюзная, д. 56   
2    г. Москва, Ленинградский просп., д. 31А, стр. 1   
3  Москва г., п. Мосрентген, Ленинский район, пос...   
4                        г. Москва, ул. Балчуг, д. 7   

                                          Размещение  
0            ТЦ "Калужский", входная группа (1 этаж)  
1               Бизнес Центр «Cherry Tower» (1 этаж)  
2  Бизнес Центр «МонАрх», около лифта к магазину ...  
3                                 ООО ПП "Автострой"  
4  Д/О № 099/1009 Банка ГПБ (АО) "Балчуг" (1 этаж...

In [4]:
print(dat["Широта"].min())
print(dat["Широта"].max())
print(dat["\Долгота"].min())
print(dat["\Долгота"].max())

55.146749
56.010063
37.044717
37.844541


In [5]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   ID            265 non-null    int64  
 1   Широта        265 non-null    float64
 2   \Долгота      265 non-null    float64
 3   Регион        265 non-null    object 
 4   Тип региона   265 non-null    object 
 5   \Тип области  265 non-null    object 
 6   Область       265 non-null    object 
 7   Полный адрес  265 non-null    object 
 8   Размещение    265 non-null    object 
dtypes: float64(2), int64(1), object(6)
memory usage: 18.8+ KB


In [6]:
dat = dat[dat["Область"] == "Москва"]
dat["lat"] = dat["Широта"]
dat["long"] = dat["\Долгота"]
dat = dat.drop(["\Долгота", "Широта"], axis=1)

In [7]:
dat.head()

ID  Регион Тип региона \Тип области Область  \
0  529360  Москва           г            г  Москва   
1  529366  Москва           г            г  Москва   
2  529368  Москва           г            г  Москва   
4  529376  Москва           г            г  Москва   
5  529380  Москва           г            г  Москва   

                                       Полный адрес  \
0        г. Москва, ул. Профсоюзная, д. 61, корп. А   
1                 г. Москва, ул. Профсоюзная, д. 56   
2   г. Москва, Ленинградский просп., д. 31А, стр. 1   
4                       г. Москва, ул. Балчуг, д. 7   
5  г. Москва, Каширское ш., д. 61, стр. 3А, корп. 1   

                                          Размещение        lat       long  
0            ТЦ "Калужский", входная группа (1 этаж)  55.655923  37.541505  
1               Бизнес Центр «Cherry Tower» (1 этаж)  55.670133  37.552418  
2  Бизнес Центр «МонАрх», около лифта к магазину ...  55.783686  37.560107  
4  Д/О № 099/1009 Банка ГПБ (АО) "Балчуг" (1 этаж...  55.746765  37.626585  
5                                       АТЦ "Москва"  55.617276  37.715622

In [8]:
open_data = pd.read_csv("/home/vitt/Документы/data/torgovl_stat.csv")

In [9]:
types = []
lats = []
longs = []
for line in open_data.geoData:
    typ = line.split(", ")[0].split('=')[1]
    lat = line.split(", ")[1].split('[')[1]
    long = line.split(", ")[2].split(']')[0]
    types.append(typ)
    lats.append(lat)
    longs.append(long)


In [10]:
open_df = pd.DataFrame({'types':types,
                       'lat':lats,
                       'long':longs})

In [11]:
open_df = open_df.astype({'lat': 'float64', 'long': 'float64'})

In [12]:
print(open_df.lat.min())
print(open_df.lat.max())
print(open_df.long.min())
print(open_df.long.max())

36.849210000000014
37.947174
55.21321260362444
56.01441183329691


In [11]:
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: GTK3Agg


In [14]:
open_df["lat_int"] = np.round(open_df["lat"],2)
open_df["long_int"] = np.round(open_df["long"],2)

In [15]:
open_df.head()

types        lat       long  lat_int  long_int
0  Point  37.564782  55.783361    37.56     55.78
1  Point  37.594849  55.786559    37.59     55.79
2  Point  37.749819  55.647955    37.75     55.65
3  Point  37.578783  55.780188    37.58     55.78
4  Point  37.678140  55.752482    37.68     55.75

In [16]:
# plt.scatter(open_df.lat_int.unique()[:77], open_df.long_int.unique())
# plt.scatter(dat.long, dat.lat)

In [17]:
from sklearn.cluster import KMeans

In [30]:
kmeans = KMeans(n_clusters=253)
kmeans.fit(open_df[["lat","long"]])

KMeans(n_clusters=253)

In [31]:
y_means = kmeans.predict(open_df[["lat","long"]])

In [32]:
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200)

In [36]:
plt.scatter(open_df.lat, open_df.long, s=5)
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=20)
plt.scatter(dat.long, dat.lat, c='red', s=10)

In [31]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
lamb = x*200*0.01
lamb

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [42]:
base = 4
y_2 = np.exp(-lamb)*lamb**base/(np.math.factorial(base))
# y_2 = lamb**base/(np.math.factorial(base))
y_2

array([0.00000000e+00, 9.02235222e-02, 1.95366815e-01, 1.33852618e-01,
       5.72522885e-02, 1.89166374e-02, 5.30859947e-03, 1.33100030e-03,
       3.07296050e-04, 6.66159314e-05])

In [43]:
plt.plot(x, y_2)